apiVersion: v1
kind: Service
metadata:
  labels:
    app: graph-disputes-server
  name: graph-disputes-server
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: graph-disputes-server