apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        app: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
        - image: "graph-disputes-frontend"
          name: graph-disputes-frontend
          