apiVersion: v1
kind: Service
metadata:
  labels:
    app: graph-disputes-server
  name: graph-disputes-server-ext
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: graph-disputes-server