"""make indexer id nullable

Revision ID: 0a4da3e8d061
Revises: 1d6e912df503
Create Date: 2021-08-09 13:12:16.881045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4da3e8d061'
down_revision = '1d6e912df503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indexer', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indexer', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
