"""make indexer metadata nullable

Revision ID: 1d6e912df503
Revises: 3ddcb30210b0
Create Date: 2021-08-09 13:04:06.776583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6e912df503'
down_revision = '3ddcb30210b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
