"""drop indexer table id col

Revision ID: 294b345c4911
Revises: d9f896813d20
Create Date: 2021-08-04 14:30:37.791995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294b345c4911'
down_revision = 'd9f896813d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexer', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexer', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
