"""add nullable to disputes

Revision ID: 3ddcb30210b0
Revises: c5d0a5062aa4
Create Date: 2021-08-09 13:00:47.251189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddcb30210b0'
down_revision = 'c5d0a5062aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
