"""make indexer datetime default to current time

Revision ID: 5e63b2f8ab2b
Revises: 294b345c4911
Create Date: 2021-08-04 16:11:28.695693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e63b2f8ab2b'
down_revision = '294b345c4911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
