"""make disputes unique and use upsert

Revision ID: 5f6805babf4e
Revises: a2d457a4ae4e
Create Date: 2021-09-07 18:25:11.655095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f6805babf4e'
down_revision = 'a2d457a4ae4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disputes', 'id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('disputes', 'dispute_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('disputes', 'current_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('current_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('disputes', 'dispute_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disputes', 'id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
