"""add datetime to dispute

Revision ID: 689d077b3e86
Revises: 7326125c8cc8
Create Date: 2021-09-07 18:17:43.409448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '689d077b3e86'
down_revision = '7326125c8cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'updated_at')

    # ### end Alembic commands ###
