"""drop stage for disputes

Revision ID: a2d457a4ae4e
Revises: 689d077b3e86
Create Date: 2021-09-07 18:19:45.512231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2d457a4ae4e'
down_revision = '689d077b3e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
