"""make upload data_kind an enum

Revision ID: bf38668628e4
Revises: 0a4da3e8d061
Create Date: 2021-08-09 16:48:45.813916

"""
from alembic import op
from sqlalchemy.dialects import postgresql

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf38668628e4"
down_revision = "0a4da3e8d061"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_kind_enum = postgresql.ENUM(
        "poi",
        "entities",
        name="data_kind_enum",
    )
    data_kind_enum.create(op.get_bind())

    op.add_column(
        "indexer_uploads",
        sa.Column(
            "data_kind_enum",
            sa.Enum("poi", "entities", name="data_kind_enum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer_uploads", "data_kind_enum")
    data_kind_enum = postgresql.ENUM(
        "poi",
        "entities",
        name="data_kind_enum",
    )
    data_kind_enum.drop(op.get_bind())

    # ### end Alembic commands ###
