"""create enum field for dispute

Revision ID: c5d0a5062aa4
Revises: 
Create Date: 2021-08-09 11:48:09.547471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "c5d0a5062aa4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dispute_stage = postgresql.ENUM(
        "waiting_for_poi",
        "acquired_poi",
        "generated_divergent_blocks",
        "arbitrating",
        "dispute_settled",
        name="dispute_stage",
    )
    dispute_stage.create(op.get_bind())

    op.add_column(
        "disputes",
        sa.Column(
            "dispute_stage",
            sa.Enum(
                "waiting_for_poi",
                "acquired_poi",
                "generated_divergent_blocks",
                "arbitrating",
                "dispute_settled",
                name="dispute_stage",
            ),
            nullable=True,
        ),
    )
    op.add_column("disputes", sa.Column("subgraph_id", sa.String(), nullable=True))
    op.add_column(
        "divergent_blocks", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        "divergent_indexer_pair",
        "divergent_blocks",
        ["dispute_id", "indexer_id_1", "indexer_id_2"],
        unique=True,
    )
    op.alter_column(
        "indexer", "id", existing_type=sa.BIGINT(), nullable=False, autoincrement=True
    )
    op.alter_column("indexer", "indexer_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("indexer", "indexer_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "indexer", "id", existing_type=sa.BIGINT(), nullable=True, autoincrement=True
    )
    op.drop_index("divergent_indexer_pair", table_name="divergent_blocks")
    op.drop_column("divergent_blocks", "updated_at")
    op.drop_column("disputes", "subgraph_id")
    op.drop_column("disputes", "dispute_stage")
    dispute_stage = postgresql.ENUM(
        "waiting_for_poi",
        "acquired_poi",
        "generated_divergent_blocks",
        "arbitrating",
        "dispute_settled",
        name="dispute_stage",
    )
    dispute_stage.drop(op.get_bind())
    # ### end Alembic commands ###
