"""generate base dispute tables

Revision ID: d9f896813d20
Revises: 
Create Date: 2021-08-04 14:26:55.623587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9f896813d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dispute_id', sa.String(), nullable=True),
    sa.Column('current_time', sa.DateTime(), nullable=False),
    sa.Column('indexer_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divergent_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('dispute_id', sa.String(), nullable=True),
    sa.Column('indexer_id_1', sa.String(), nullable=True),
    sa.Column('indexer_id_2', sa.String(), nullable=True),
    sa.Column('divergent_blocks', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexer',
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('indexer_id', sa.String(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('indexer_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('indexer_id')
    )
    op.create_table('indexer_uploads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('dispute_id', sa.String(), nullable=True),
    sa.Column('indexer_id', sa.String(), nullable=True),
    sa.Column('data_path', sa.String(), nullable=True),
    sa.Column('data_kind', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('indexer_uploads')
    op.drop_table('indexer')
    op.drop_table('divergent_blocks')
    op.drop_table('disputes')
    # ### end Alembic commands ###
