"""create indexer metadata

Revision ID: e5d6dcc9c7fe
Revises: 
Create Date: 2021-09-07 17:59:50.944470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5d6dcc9c7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexer_id', sa.String(), nullable=True),
    sa.Column('dispute_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('indexer_indexer_id_idx', table_name='indexer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('indexer_indexer_id_idx', 'indexer', ['indexer_id'], unique=False)
    op.drop_table('indexer_metadata')
    # ### end Alembic commands ###
