name: Production CI/CD
on:
  push:
    paths:
    - 'server/**'
    - '.k8s/**'
    - '.github/**'
env:
  BASE_IMAGE: ghcr.io/edgeandnode/graph-disputes-server
  APP_NAME: graph-disputes-server

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        cache-from: type=registry,ref=${{ env.BASE_IMAGE }}:latest
        cache-to: type=inline
        tags: |
          ${{ env.BASE_IMAGE }}:${{ github.sha }}
          ${{ env.BASE_IMAGE }}:latest
        push: true

  deploy:
    if: github.ref == 'refs/heads/goaaron/poi_dispute_service'
    runs-on: ubuntu-latest
    needs: build-test
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: ${{ secrets.GCP_CLUSTER_NAME }}
        location: ${{ secrets.GCP_CLUSTER_LOCATION }}
        credentials: ${{ secrets.GCP_SA_KEY_PRODUCTION }}

    - name: Set a new k8s image and apply the manifests
      run: .github/scripts/kustomize-apply.sh mainnet $APP_NAME=$BASE_IMAGE:$GITHUB_SHA

    - name: Wait for pod to be ready
      run: kubectl rollout status statefulset $APP_NAME --timeout=5m
